### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply/BAT0/capacity' when trying to initialize "wmcompanion.events.power.PowerActions"

### ISSUE THREAD

**Issue by xTrayambak** [kriansa/wmcompanion#4]
Greetings, so, I have this snippet of code here:

```python
from wmcompanion.events.power import PowerActions
```

when I run it, it seems that WMCompanion runs into an error whilst trying to connect with the "/sys/class/power_supply/BAT0/capacity" file, necessary for PowerActions to work. This is because many systems actually store this file at "/sys/class/power_supply/BAT1/capacity" or "/sys/class/power_supply/BAT2/capacity" and so on and so forth. This same issue occured in bpytop and was fixed via a merge. I can attempt to fix this via a merge as well if needed. (this is the fix in bpytop -> https://github.com/lwhsu/bpytop/commit/6643dc2605f4eca017c2c5b53ee902c11670157a).

Regards,
Trayambak.

**Comment by xTrayambak** [comment]
![image](https://user-images.githubusercontent.com/59499552/197786118-42372bd8-867c-4a91-a760-5ede13a320ff.png)
 After a bit of tinkering, it seems this (line 202 of wmcompanion/events/power.py) is the causative code. This is not designed to handle anything apart from BAT0.

**Comment by kriansa** [comment]
Good finding. Yes, there are several hard-coded `BAT0` instances in power.py that would need to be refactored in order to fully support non-0 indexes by default. I'll take a look at that.

**Comment by xTrayambak** [comment]
I've mashed up a fix for it, it **kinda** works. Would you like to check it out?

**Comment by kriansa** [comment]
@xTrayambak I just pushed a fix for it on `main`, would you mind testing and see if it works out for you?

**Comment by xTrayambak** [comment]
Sure.

**Comment by xTrayambak** [comment]
Yeah, it works now. Thanks!
